#!/bin/sh

# The non-nested backtick syntax is the only way this works in the old
# /bin/sh on Solaris 8.
getAbsoluteDir()
{
    ( cd `dirname "$1"` ; pwd )
}

BIN_DIR=`getAbsoluteDir "$0"`
TOP_DIR=`dirname "$BIN_DIR"`
CLS_DIR="$TOP_DIR"/share/java

java -Denv.PATH="$PATH" -classpath "$CLS_DIR" Which "$@"

