#!/bin/sh

BIN_DIR=$(dirname "$0")
if [ "$BIN_DIR" = "." ]
then
	BIN_DIR=$(pwd)
fi

TOP_DIR=$(dirname "$BIN_DIR")
CLS_DIR="$TOP_DIR"/share/java

java -Denv.PATH="$PATH" -classpath "$CLS_DIR" Which "$@"

